baseURL = 'http://brettg.cc'
languageCode = 'en-us'
title = "Brett Grady's Technical Blog"

[params] 
  subtitle = "One day I'll clean this up :)"

[markup]
  [markup.highlight]
    noClasses = false
